CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(255) NOT NULL,
	"body" varchar(255) NOT NULL,
	"date" timestamp DEFAULT now(),
	"area" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"email" varchar(255),
	"name" varchar(255),
	"phone" varchar(255),
	"credits" integer DEFAULT 3,
	"subscription_expiration_date" varchar(255),
	"raw_user_meta_data" json,
	CONSTRAINT "profiles_email_unique" UNIQUE("email"),
	CONSTRAINT "profiles_phone_unique" UNIQUE("phone")
);
--> statement-breakpoint
CREATE TABLE "scrapers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scrapers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company" varchar(255),
	"frequency" integer DEFAULT 5,
	"last_update" bigint,
	"last_ping" bigint,
	"services" text[] DEFAULT '{}',
	"params" json DEFAULT '{}'::json
);
--> statement-breakpoint
CREATE TABLE "services" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"notification" varchar(255) NOT NULL,
	"notification_within" varchar(255) NOT NULL,
	"options" json DEFAULT '{}'::json
);
--> statement-breakpoint
CREATE UNIQUE INDEX "services_user_name_unique" ON "services" USING btree ("user","name");